### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by totora0155** [totora0155/lll#5]
- [x] cloud(tag, category, and so on)
- [x] sort
- [x] pager
- [ ] seo
- [x] rss(atom)
- [ ] helper method
- [ ] blog themes
- [x] plugin, gulp etc...

**Comment by totora0155** [comment]
- [ ] ~~rssStream~~
- [ ] ~~jsonStream~~

**Comment by totora0155** [comment]
- [ ] atom entry > category + tag?

**Comment by totora0155** [comment]
default
title -> capitalize `name`
